### ISSUE TITLE
Commands that return NoneType or other non-string types don't get logged and throw an error

### ISSUE THREAD

**Issue by utf-4096** [piqueserver/piqueserver#784]
**Describe the bug**

When running a command that does not return anything or returns any non-string type, the command does not get logged and an error is thrown.

**To Reproduce**

1. Join server
2. Run command '/kill'
3. See error

**Expected behavior**

Command gets logged correctly and no error is thrown.

**Stack Trace or logs**

```
2024-05-15T23:10:15+0200 [stderr#error] Traceback (most recent call last):
2024-05-15T23:10:15+0200 [stderr#error]   File "/opt/piqueserver/venv/lib/python3.11/site-packages/pyspades/protocol.py", line 170, in update
2024-05-15T23:10:15+0200 [stderr#error]     self.data_received(peer, event.packet)
2024-05-15T23:10:15+0200 [stderr#error]   File "/opt/piqueserver/venv/lib/python3.11/site-packages/piqueserver/server.py", line 808, in data_received
2024-05-15T23:10:15+0200 [stderr#error]     ServerProtocol.data_received(self, peer, packet)
2024-05-15T23:10:15+0200 [stderr#error]   File "/opt/piqueserver/venv/lib/python3.11/site-packages/pyspades/protocol.py", line 122, in data_received
2024-05-15T23:10:15+0200 [stderr#error]     connection.loader_received(packet)
2024-05-15T23:10:15+0200 [stderr#error]   File "/opt/piqueserver/venv/lib/python3.11/site-packages/pyspades/player.py", line 137, in loader_received
2024-05-15T23:10:15+0200 [stderr#error]     call_packet_handler(self, loader)
2024-05-15T23:10:15+0200 [stderr#error]   File "pyspades/packet.pyx", line 131, in pyspades.packet.call_packet_handler
2024-05-15T23:10:15+0200 [stderr#error]   File "/opt/piqueserver/venv/lib/python3.11/site-packages/pyspades/player.py", line 647, in on_chat_message_recieved
2024-05-15T23:10:15+0200 [stderr#error]     self.on_command(*parse_command(value[1:]))
2024-05-15T23:10:15+0200 [stderr#error]   File "/opt/piqueserver/venv/lib/python3.11/site-packages/piqueserver/scripts/map_extensions.py", line 37, in on_command
2024-05-15T23:10:15+0200 [stderr#error]     return connection.on_command(self, command, parameters)
2024-05-15T23:10:15+0200 [stderr#error]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-15T23:10:15+0200 [stderr#error]   File "/opt/piqueserver/venv/lib/python3.11/site-packages/piqueserver/player.py", line 135, in on_command
2024-05-15T23:10:15+0200 [stderr#error]     result = commands.handle_command(self, command, parameters)
2024-05-15T23:10:15+0200 [stderr#error]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-15T23:10:15+0200 [stderr#error]   File "/opt/piqueserver/venv/lib/python3.11/site-packages/piqueserver/commands.py", line 415, in handle_command
2024-05-15T23:10:15+0200 [stderr#error]     result=escape_control_codes(result))
2024-05-15T23:10:15+0200 [stderr#error]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-15T23:10:15+0200 [stderr#error]   File "pyspades/common.pyx", line 112, in pyspades.common.escape_control_codes
2024-05-15T23:10:15+0200 [stderr#error] AttributeError: 'NoneType' object has no attribute 'replace'
```

**Server (please complete the following information):**
- Piqueserver Version: 1.2.0 (pip)

**Additional context**

Regression from #783
